### ISSUE TITLE
Kong support

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#370]
As a user I want to use Kong gateway instead of EnvoyFleet

This opens up several questions as follows:

- [ ] - In this scenario should Kong be a prerequisite or should be install Kong operator when such API is created
   a. we could trigger kong operator installation 
   b. validation webhook could prompt users to do this

- [ ] how to translate x-kusk extensions into [KongIngress](https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/references/custom-resources/#kongingress)
- [ ] Kong supports mocking out of the box. We need to translate Open API examples into Kong readable configuration https://docs.konghq.com/hub/kong-inc/mocking/

**Comment by olensmar** [comment]
Perhaps we can start with the  scenario where Kong already exists in your cluster (which to me seems more likely than that you would explicitly want to use Kong instead of Envoy) - our installer could detect this and ask if the user wants to use Kong or Envoy?

**Comment by jasmingacic** [comment]
Installer option seems to be simple way to solve this. With the mutating webhook we add envoyfleet if such is missing I thought that we could also detect whether EnvoyFleet or Kong exist in the cluster and then install accordingly.
For example:
```
apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: hello-world
spec: 
  gateway:
    type: EnvoyFleet
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
```
we could detect and install such envoy fleet if not installed. Something similar could be done for Kong:
```
apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: hello-world
spec: 
  gateway:
    type: Kong
    name: kusk-gateway-kong
    namespace: kusk-system
```

This would trigger installation of Kong cluster CRD and would configure KongIngress CRD accordingly and whatnot. Or if Kong CRD is missing, therefore Kong Operator is not installed we could trigger Kong Operator installation. Perhaps such approach could be too invasive.

**Comment by aabedraba** [comment]
For now, we're not going to support other Gateway APIs, so let's open this up in the future if we see fit.
