### ISSUE TITLE
Telemetry to Support Adoption and Usage Metrics

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#427]
Updates to telemetry for Kusk to support adoption and usage metrics. 

- [x] New Installation Events
- [x] Heartbeat from installed cluster #540 
- [x] Event on Dashboard Usage #540 
- [ ] Event on API Gateway Traffic
- [x] Ability to turn off telemetry for internal development team
- [x] Dashboard Item: New Installations by Day/Week/Month
- [x] Dashboard Item: Active Developers (CLI,Dashboard,Cluster Ops) by Day/Week/Month
- [x] Dashboard Item: Active Clusters (Heartbeat from installed clusters) by Day/Week/Month
- [ ] Dashboard Item: Active Gateways (Traffic through gateway) by Day/Week/Month

**Comment by jasmingacic** [comment]
@crjones this has been partially done with GA improvement and added version.
Points from 1,2,3,5,6 have been completed. Can you please confirm that we are on the same page?

We should check with @mortada-codes what to do about dashboard and telemetry.

**Comment by kylehodgetts** [comment]
> Dashboard Item: Active Gateways (Traffic through gateway) by Day/Week/Month

We don't believe we should be tracking this metric. For self installed envoy gateways, this information is private to the user and doesn't help us in improving Kusk Gateway as at this point, it's handled by Envoy

**Comment by aabedraba** [comment]
Heartbeat was improved, but dashboard hasn't been worked on yet. 
release 1.2.0 got the heartbeats telemetry in it

**Comment by jasmingacic** [comment]
Re: Dashboard telemetry has been moved to BE with https://github.com/kubeshop/kuskgateway-api-server/pull/56

**Comment by crjones** [comment]
Once we have active clusters showing accurate information, we should be able to call this complete.

**Comment by jasmingacic** [comment]
I've got two clusters constantly running and feed telemetry data.

**Comment by aabedraba** [comment]
@jasmingacic i think he refers to the missing property field

**Comment by jasmingacic** [comment]
The conversion between segment and pg database. I will take a deeper dive into that next week.
